services:
  - type: web
    name: chatbot-backend
    env: python
    plan: free
    buildCommand: pip install -r ai_chatbot_backend/requirements.txt
    startCommand: python -m uvicorn ai_chatbot_backend.main:app --host 0.0.0.0 --port 10000 --reload
    autoDeploy: true
